version: '3'

x-base: &base
  restart: unless-stopped
  logging:
    options:
      max-size: "1m"
      max-file: "10"

services:
  kafka-ui:
    <<: *base
    image: provectuslabs/kafka-ui:${KAFKA_UI_VERSION:-latest}
    container_name: kafka-ui
    hostname: kafka-ui
    ports:
      - '8080:8080'
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      LOGGING_LEVEL_ROOT: 'warn'
      LOGGING_LEVEL_COM_PROVECTUS: 'warn'
      SPRING_SECURITY_USER_NAME: ${KAFKA_ui_USERNAME:-user}
      SPRING_SECURITY_USER_PASSWORD: ${KAFKA_ui_PASSWORD:-password}
    volumes:
      - ./data:/etc/kafkaui
